### PR TITLE
Add appveyor.yml

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by Julian** [comment]
Hooray!

I *think* the first error there is just saying that it's finding the package from the local repo instead of the one that's been installed into the virtualenv -- can we get appveyor to cd out of the repo possibly?

**Comment by altendky** [comment]
@Julian yeah, I `-e` installed to fix that.  You don't like `src/filesystems`?  :]

I think we're up to actual test failures in the build now so it seems to be working, at least to get started.

**Comment by Julian** [comment]
> @Julian yeah, I -e installed to fix that. You don't like src/filesystems? :]

:D yeah...

Anyways, hooray! Thanks, merging.

**Comment by Julian** [comment]
(Will have a look at fixing in a few hours, I hope it should be simple...)

**Pull request merged**
