### PR TITLE
Update memory.FS to respect binary/text mode for files

### PR DESCRIPTION
**Pull request by altendky**
Ref #11

### CODE REVIEW

**Comment by altendky** [comment]
I wasn't sure if I should just be wrapping up `_BytesIOIsTerrible()` or replacing it.

**Comment by altendky** [comment]
There's the other option with `TextIOWrapper` being used directly instead of wrapping the `_BytesIOIsTerrible`.

**Comment by altendky** [comment]
@Julian, just a quick bump in case you missed this.

**Comment by Julian** [comment]
Oh, I did! Will have a look tonight -- I think I was trying to remember
whether I actually still think we're missing a test or not (basically I
want to know whether we would catch this even if we didn't support both Py2
and Py3)

**Comment by Julian** [comment]
Yeah exactly

On Apr 23, 2018 17:24, "Kyle Altendorf" <notifications@github.com> wrote:

Yeah, I suppose there is an argument for having a test that would fail in
py2 as well. Or, for the inverse bug, one that would fail in py3.
Basically, have the test that verifies it gets the proper type for both 'rb'
and 'r' (well, two tests I suppose).

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Julian/Filesystems/pull/13#issuecomment-383727992>, or mute
the thread

**Comment by Julian** [comment]
I am still super swamped, so haven't gotten a chance to look at this more carefully yet :/

**Comment by Julian** [comment]
Merged, sorry for the delay :/

**Pull request merged**
